### ISSUE TITLE
ln: failed to create symbolic link '/var/www/html/docroot/sites/default/files': No such file or directory

### ISSUE THREAD

**Issue by aawalkerjj** [snp-technologies/Azure-App-Service-Drupal7#1]
I run into this issue when the Dockerfile tries to create the symbolic link. Any idea how to fix this issue?

**Comment by snpdev** [comment]
@aawalkerjj ,

I assume you receive this message during docker build.

This problem will occur when the directory tree of your code does not match the tree assumed by this Docker solution. Our Dockerfile assumes:

1. The code is in a git repo
2. Below the root directory of the repo, there is a 'docroot' directory
3. The Drupal code is in the 'docroot' directory

We do this so that the following folders/files are outside (a level above) the website document root: 

1. .git directory 
2. .gitignore file 
3. Docker solution files

If you want to have your code in /var/www/html, without the 'docroot' directory, you can edit the solution files.

I hope this is helpful. Let us know if you have any suggestions to improve on this Docker solution for Azure.

Thanks - Mike

**Comment by snpdev** [comment]
@aawalkerjj, just checking in to see if you had success with your deployment. I am interested in your outcome.
